fail_fast: true
repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black deepsearch_glm
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black tests
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort deepsearch_glm
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: system
        name: MyPy
        entry: poetry run mypy deepsearch_glm
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: system
        name: Pylint
        entry: poetry run pylint --jobs 0 --disable=E0611 deepsearch_glm
        #entry: poetry run pylint --errors-only --jobs 0 --disable=E0611 deepsearch_glm
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: system
        name: Poetry check
        entry: poetry lock --check
        pass_filenames: false
        language: system
