fail_fast: true
repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff formatter
        entry: uv run ruff format deepsearch_glm tests
        pass_filenames: false
        language: system
        files: '\.py$'
      - id: ruff-lint
        name: Ruff linter
        entry: uv run ruff check --fix deepsearch_glm tests
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: system
        name: MyPy
        entry: uv run mypy deepsearch_glm
        pass_filenames: false
        language: system
        files: '\.py$'
      - id: system
        name: MyPy
        entry: uv run mypy tests
        pass_filenames: false
        language: system
        files: '\.py$'
  - repo: local
    hooks:
      - id: system
        name: uv lock
        entry: uv lock --check
        pass_filenames: false
        language: system
