on:
  workflow_call:

env:
  CMAKE_BUILD_TYPE: Debug

jobs:
  run-checks:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      # - name: Install dependencies [linux]
      #   run: sudo apt-get install -y libldap-common
      #   shell: bash
      - uses: ./.github/actions/setup-uv
        with:
          python-version: ${{ matrix.python-version }}
          run_install: 'false'

      - name: Compile and install
        run: |
          uv sync
          ls -l
          ls -l deepsearch_glm
      
      - name: Test interface without extras
        run: |
          uv run pytest ./tests/test_simple_interface.py -vs
      - name: Install extras
        run: |
          uv sync --all-extras
          ls -l
          ls -l deepsearch_glm
      - name: Run styling check
        run: uv run pre-commit run --all-files
      - name: Testing
        run: |
          uv run pytest ./tests/test_structs.py -v
          uv run pytest ./tests/test_nlp.py -v
          uv run pytest ./tests/test_glm.py -v
      - name: Build with uv
        run: uv build
